# Generated by Django 4.2.7 on 2023-11-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_user_alter_subject_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subjectvisevideo',
            name='user',
        ),
    ]
