# Generated by Django 4.2.7 on 2023-11-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subjectvisevideo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectvisevideo',
            name='user',
        ),
    ]
