# Generated by Django 4.2.7 on 2023-11-06 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_subjectvisevideo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectvisevideo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
