# Generated by Django 4.2.7 on 2023-11-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subjectvisevideo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
