# Generated by Django 4.2.7 on 2023-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bagroundcolor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectvisevideo',
            name='timestamp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
