# Generated by Django 4.2.7 on 2023-11-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_subject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
    ]
