# Generated by Django 4.2.7 on 2023-11-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_subject_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectvisevideo',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
    ]
