# Generated by Django 4.2.7 on 2023-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_subjectvisevideo_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
