# Generated by Django 4.2.7 on 2023-11-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_course_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='count',
            new_name='video_count',
        ),
    ]
