# Generated by Django 4.2.7 on 2023-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_subject_user_alter_subjectvisevideo_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPredefinedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_subject', models.CharField(default='Default Subject', max_length=255)),
                ('default_bagroundcolor', models.CharField(default='Default Color', max_length=50)),
            ],
        ),
    ]
