# Generated by Django 4.2.7 on 2023-11-17 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_globalpredefineddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalPredefinedData',
        ),
        migrations.AddField(
            model_name='subjectvisevideo',
            name='is_finished_by_users',
            field=models.ManyToManyField(related_name='finished_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
