# Generated by Django 4.2.7 on 2023-11-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_globalpredefineddata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subjectvisevideo',
            name='user',
        ),
    ]
