# Generated by Django 4.2.7 on 2023-11-17 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_subject_user_remove_subjectvisevideo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectvisevideo',
            name='is_finished_by_users',
        ),
        migrations.RemoveField(
            model_name='subjectvisevideo',
            name='is_finish',
        ),
        migrations.AddField(
            model_name='subjectvisevideo',
            name='is_finish',
            field=models.ManyToManyField(related_name='finished_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
